services:
  - type: web
    name: reaback
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx tsx src/server.ts
    envVars:
      - key: NODE_ENV
        value: production
