services:
  - type: web
    name: reaback
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx tsx src/server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://reafront-sage.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
